apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-pod
  name: test-pod
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - command:
    - /bin/sh
    - -c
    - tail -f /dev/null
    image: alpine:latest
    imagePullPolicy: Always
    name: console
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
